name: Deploy application

# run workflow on every push
on:
  push:
    branches:
      - main
    paths:
      - 'repo/ofodi-works/**'

jobs:
  deploy:
    # run workflow on ubuntu with permissions
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      # setup latest node version
      - uses: actions/setup-node@v1
        with:
          node-version: "18"
          
      - name: Use AWS credentials
        run: |
          aws ec2 describe-instances
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.aws.outputs.access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.aws.outputs.secret_access_key }}
        

      # We need to configure AWS creds using aws actions to deploy code on AWS EC2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::794948059597:role/deployGit
          aws-region: eu-north-1
