name: CICD

on:
  push:
    branches: [ "master" ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      
     
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t ofodic065/tcoc_frontend .
      - name: Publish image to docker hub
        run: docker push ofodic065/tcoc_frontend:latest
        
  deploy:
    needs: buildx
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        
      - name: Pull image from docker hub
        run: docker pull ofodic065/tcoc_frontend:latest
      - name: Delete old container
        run: docker rm -f tcoc_frontend-container
      - name: Run docker container
        run: docker run -d -p 3000:80 --name tcoc_frontend-container ofodic065/tcoc_frontend
