name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with: 
        context: .
        push: true
        tags: ofodic065/tcoc_frontend:${{ github.sha }}
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ec2-13-50-145-153.eu-north-1.compute.amazonaws.com
        username: ubuntu
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          docker stop tcoc_frontend || true
          docker rm tcoc_frontend || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/tcoc_frontend:${{ github.sha }}
          docker run -d --name tcoc_frontend -p 80:80 ${{ secrets.DOCKER_USERNAME }}/tcoc_frontend:${{ github.sha }}
