name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build-test-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with: 
        context: .
        push: true
        tags: ofodic065/tcoc_frontend:${{ github.sha }}
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker stop tcoc_frontend || true
          docker rm tcoc_frontend || true
          docker pull ${{ secrets.DOCKER_USERNAME }}/tcoc_frontend:${{ github.sha }}
          docker run -d --name tcoc_frontend -p 80:80 ${{ secrets.DOCKER_USERNAME }}/tcoc_frontend:${{ github.sha }}
